[Domain]
name = "example.com"
vcpu = 1
memory = 1024
swap = 0
disksize = 10
diskpath = "/var/lib/libvirt/images/example.com.qcow2.img"
root_password = "password"
arch = "x86_64"
os_type = "linux"
os_variant = "rhel7"

[[Domain.Network]]
interface = "br0"
ip = "192.168.0.2"
netmask = "255.255.255.0"
default_gateway = "192.168.0.1"
nameserver = "8.8.8.8"

[[Domain.Network]]
interface = "br1"
ip = "192.168.1.2"
netmask = "255.255.255.0"

[Image]
location = "/var/lib/libvirt/images/CentOS-7-x86_64-DVD-1503-01.iso"

[Template]
server = "192.168.0.9"
file = "layout.html"
